import {Component,inject,signal} from '@angular/core';
import {CommonModule} from '@angular/common';
import {FormsModule,NgForm} from '@angular/forms';
import {MAT_DIALOG_DATA,MatDialogRef} from '@angular/material/dialog';
import {Api,Module,Row,Field,errorText} from './api';
import {MATERIAL} from './material';
import {ClinicalFields} from './clinical-fields';
import {PageFields} from './page-fields';
import {FileInput} from './file-input';
@Component({standalone:true,imports:[CommonModule,FormsModule,ClinicalFields,PageFields,FileInput,...MATERIAL],template:`
  <h2 mat-dialog-title>{{original.id?'Editar':'Nuevo registro'}} · {{module.label}}</h2>
  <form #form="ngForm" (ngSubmit)="save(form)"><mat-dialog-content>
    @if(error()){<p class="error-banner">{{error()}}</p>}
    <div class="form-grid">@for(f of module.fields;track f.name){@if(!skip(f)){<div [class.full-width]="f.type==='textarea'||f.type==='json'">
      @if(f.reference){<div class="lookup-search"><input [attr.aria-label]="'Buscar '+f.label" [placeholder]="'Buscar '+f.label.toLowerCase()+'…'" (input)="searchLookup(f,$any($event.target).value)"></div>}
      @if(isFile(f)){<app-file-input [label]="f.label" [(value)]="model[f.name]" [multiple]="f.type==='json'" [publish]="module.key==='aplicacion'" [module]="module.key" [record]="original.id||''"/>}@else{<mat-form-field appearance="outline"><mat-label>{{f.label}}</mat-label>
        @if(f.type==='boolean'){<mat-select [name]="f.name" [(ngModel)]="model[f.name]"><mat-option [value]="true">Sí</mat-option><mat-option [value]="false">No</mat-option></mat-select>}@else if(f.options||f.reference){<mat-select [name]="f.name" [(ngModel)]="model[f.name]" [required]="f.required" (selectionChange)="selected(f)"><mat-option [value]="null">Sin seleccionar</mat-option>@if(f.options){@for(option of f.options;track option){<mat-option [value]="option">{{optionLabel(option)}}</mat-option>}}@else{@for(option of lookups()[f.name]||[];track option.id){<mat-option [value]="option.id">{{option.label}}</mat-option>}}</mat-select>}
        @else if(f.type==='textarea'||f.type==='json'){<textarea matInput [name]="f.name" [(ngModel)]="model[f.name]" [required]="f.required" rows="4"></textarea>}
        @else{<input matInput [name]="f.name" [(ngModel)]="model[f.name]" [type]="f.type" [required]="f.required&&!f.secret" [attr.maxlength]="f.maxLength||null" [step]="f.type==='number'?'any':null" (ngModelChange)="changed(f)" [autocomplete]="f.secret?'new-password':'off'">}
        @if(f.secret){<mat-hint>{{original.id?'Deja vacío para conservar el valor actual':'Opcional para usuarios que no inician sesión'}}</mat-hint>}
      </mat-form-field>}</div>}}</div>
    @if(module.key==='facturas'){<section class="invoice-editor"><h3>Conceptos de la factura</h3>@for(item of items;track $index;let i=$index){<div class="invoice-line"><mat-form-field appearance="outline"><mat-label>Concepto</mat-label><input matInput [(ngModel)]="item.nombre_cuenta" [name]="'concepto'+i" required></mat-form-field><mat-form-field appearance="outline"><mat-label>Cantidad</mat-label><input matInput type="number" min="1" [(ngModel)]="item.cantidad" [name]="'cantidad'+i" required></mat-form-field><mat-form-field appearance="outline"><mat-label>Precio</mat-label><input matInput type="number" min="0" step="0.01" [(ngModel)]="item.precio" [name]="'precio'+i" required></mat-form-field><button mat-icon-button type="button" (click)="items.splice(i,1)" aria-label="Quitar concepto"><mat-icon>delete_outline</mat-icon></button></div>}<button mat-stroked-button type="button" (click)="items.push({nombre_cuenta:'',cantidad:1,precio:0})"><mat-icon>add</mat-icon>Agregar concepto</button><p class="invoice-total">Total estimado: <strong>{{total()|number:'1.2-2'}}</strong></p></section>}
  @if(module.key==='recetas'){<app-clinical-fields [model]="model"/>}@if(module.key==='paginas'){<app-page-fields [page]="model['pagina']" [content]="model['contenido']"/>}@if(module.key==='citas'){<mat-form-field appearance="outline"><mat-label>Horario disponible</mat-label><mat-select (selectionChange)="chooseSlot($event.value)" [value]="model['hora_inicio']">@for(s of slots();track s.inicio){<mat-option [value]="s.inicio">{{s.inicio}} – {{s.fin}}</mat-option>}</mat-select><mat-hint>Selecciona médico y fecha para consultar disponibilidad.</mat-hint></mat-form-field>} </mat-dialog-content><mat-dialog-actions align="end"><button mat-button type="button" [disabled]="saving()" (click)="dialog.close()">Cancelar</button><button mat-flat-button type="submit" [disabled]="saving()">{{saving()?'Guardando…':'Guardar cambios'}}</button></mat-dialog-actions></form>
`})
export class Editor {
  slots=signal<{inicio:string;fin:string}[]>([]);
  isFile(f:Field){return ['foto','archivo','logotipo','icono_sitio'].includes(f.name);}
  specialJson(f:Field){return this.isFile(f)||(this.module.key==='recetas'&&f.name.startsWith('informacion_'))||(this.module.key==='paginas'&&f.name==='contenido');}
  skip(f:Field){return f.readOnly||(this.module.key==='recetas'&&f.name.startsWith('informacion_'))||(this.module.key==='paginas'&&f.name==='contenido')||(this.module.key==='citas'&&['hora_inicio','hora_fin'].includes(f.name));}
  changed(f:Field){if(this.module.key==='citas'&&f.name==='fecha_cita')this.refreshSlots();}
  selected(f:Field){if(this.module.key==='citas'&&f.name==='medico_id')this.refreshSlots();if(f.name.startsWith('plantilla_')&&f.reference&&this.model[f.name])this.api.get<Row>('/records/'+f.reference+'/'+this.model[f.name]).subscribe({next:r=>{this.model[this.module.key==='informes'?'informe':'mensaje']=r['plantilla']||r['mensaje']||'';},error:e=>this.error.set(errorText(e))});}
  refreshSlots(){if(!this.model['medico_id']||!this.model['fecha_cita'])return;this.api.get<{inicio:string;fin:string}[]>('/slots',{medico:this.model['medico_id'],fecha:this.model['fecha_cita'],exclude:this.original.id||0}).subscribe({next:s=>this.slots.set(s),error:e=>this.error.set(errorText(e))});}
  chooseSlot(start:string){const s=this.slots().find(s=>s.inicio===start);if(s){this.model['hora_inicio']=s.inicio;this.model['hora_fin']=s.fin;}}
  data=inject<{module:Module;row?:Row}>(MAT_DIALOG_DATA);dialog=inject(MatDialogRef<Editor>);api=inject(Api);module=this.data.module;original:Partial<Row>=this.data.row||{};model:Record<string,any>={};items:any[]=[];saving=signal(false);error=signal('');lookups=signal<Record<string,{id:string;label:string}[]>>({});timers:Record<string,ReturnType<typeof setTimeout>>={};
  constructor(){for(const f of this.module.fields){let v=this.original[f.name];if(f.secret)v='';else if(v!=null&&f.type==='json'&&!this.specialJson(f))v=typeof v==='string'?v:JSON.stringify(v,null,2);else if(v!=null&&f.reference)v=String(v);else if(v!=null&&f.options)v=String(v);else if(v&&f.type==='date')v=String(v).slice(0,10);else if(v&&f.type==='datetime-local')v=String(v).slice(0,16);this.model[f.name]=v??(f.name==='estado'&&f.options?.includes('1')?'1':f.name==='tipo_turno'?'Sequential':null);if(f.reference)this.lookup(f,'');} for(const key of ['informacion_medicamentos','informacion_diagnosticos']){let v=this.model[key];if(typeof v==='string'){try{v=JSON.parse(v);}catch{v=[];}}this.model[key]=Array.isArray(v)?v:[];} if(this.module.key==='paginas'){let v=this.original.contenido;try{if(typeof v==='string')v=JSON.parse(v);}catch{v={};}this.model['contenido']=v||{};} if(this.module.key==='citas')this.refreshSlots();this.items=this.original.items?structuredClone(this.original.items):[{nombre_cuenta:'',cantidad:1,precio:0}];}
  searchLookup(f:Field,text:string){clearTimeout(this.timers[f.name]);this.timers[f.name]=setTimeout(()=>this.lookup(f,text),300);}
  lookup(f:Field,search:string){this.api.get<{rows:{id:string;label:string}[]}>('/lookups/'+f.reference,{search}).subscribe({next:d=>{const rows=d.rows.map(r=>({...r,id:String(r.id)}));const selected=this.model[f.name];if(selected&&!rows.some(r=>r.id===String(selected)))rows.unshift({id:String(selected),label:'Registro '+selected});this.lookups.update(v=>({...v,[f.name]:rows}));},error:e=>this.error.set(errorText(e))});}
  optionLabel(v:string){return ({'0':'Inactivo','1':'Activo',Monday:'Lunes',Tuesday:'Martes',Wednesday:'Miércoles',Thursday:'Jueves',Friday:'Viernes',Saturday:'Sábado',Sunday:'Domingo',male:'Masculino',female:'Femenino',Credit:'Ingreso',Debit:'Egreso',Pending:'Pendiente',Processing:'En proceso',Completed:'Completado',Failed:'Fallido',Sequential:'Secuencial',Timestamp:'Por horario'} as Record<string,string>)[v]||v;}
  total(){const subtotal=this.items.reduce((s,i)=>s+Number(i.cantidad||0)*Number(i.precio||0),0);return subtotal*(1-Number(this.model['porcentaje_descuento']||0)/100)*(1+Number(this.model['porcentaje_iva']||0)/100);}
  save(form:NgForm){if(form.invalid){form.control.markAllAsTouched();return;}this.saving.set(true);this.error.set('');const body={...this.model,...(this.module.key==='facturas'?{items:this.items}:{})};const path='/records/'+this.module.key;const request=this.original.id?this.api.put(path+'/'+this.original.id,body):this.api.post(path,body);request.subscribe({next:()=>this.dialog.close(true),error:e=>{this.error.set(errorText(e));this.saving.set(false);}});}
}
