import {Component,Input,Output,EventEmitter,inject,signal} from '@angular/core';
import {MATERIAL} from './material';
import {Api,errorText} from './api';
@Component({selector:'app-file-input',standalone:true,imports:[...MATERIAL],template:`<div class="file-field"><label>{{label}}</label><input type="file" accept=".pdf,.png,.jpg,.jpeg,.webp" [multiple]="multiple" (change)="upload($event)" [disabled]="busy()" [attr.aria-label]="label">@if(busy()){<mat-progress-bar mode="indeterminate"/>}@if(error()){<p class="error-banner">{{error()}}</p>}@for(url of files();track url){<div class="file-chip"><button mat-button type="button" (click)="open(url)"><mat-icon>attach_file</mat-icon>Ver archivo</button><button mat-icon-button type="button" (click)="remove(url)" aria-label="Quitar archivo"><mat-icon>close</mat-icon></button></div>}</div>`})
export class FileInput {
 @Input() label='Archivo';@Input() value:any;@Input() multiple=false;@Input() publish=false;@Input() module='';@Input() record='';@Output() valueChange=new EventEmitter<any>();api=inject(Api);busy=signal(false);error=signal('');
 files():string[]{if(!this.value)return[];if(Array.isArray(this.value))return this.value;try{const parsed=JSON.parse(this.value);if(Array.isArray(parsed))return parsed;}catch{}return [String(this.value)];}
 upload(event:Event){const files=Array.from((event.target as HTMLInputElement).files||[]);if(!files.length)return;this.busy.set(true);this.error.set('');let pending=files.length;for(const file of files)this.api.upload(file,this.publish).subscribe({next:d=>{const url=this.publish?'/api/public/files/'+d.id:d.url;const values=this.multiple?[...this.files(),url]:[url];this.value=this.multiple?values:url;this.valueChange.emit(this.value);if(--pending===0)this.busy.set(false);},error:e=>{this.error.set(errorText(e));if(--pending===0)this.busy.set(false);}});}
 remove(url:string){const values=this.files().filter(f=>f!==url);this.value=this.multiple?values:values[0]||null;this.valueChange.emit(this.value);}
 open(url:string){if(url.startsWith('/api/public/')){window.open(url,'_blank','noopener');return;}if(!url.startsWith('/api/files/'))return;this.api.blob(url.slice(4),{module:this.module,record:this.record}).subscribe({next:b=>{const u=URL.createObjectURL(b);window.open(u,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(u),60000);},error:e=>this.error.set(errorText(e))});}
}
