import {Component,Input} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {MATERIAL} from './material';
import {FileInput} from './file-input';
@Component({selector:'app-page-fields',standalone:true,imports:[FormsModule,FileInput,...MATERIAL],template:`<h3>Contenido de la página</h3><div class="form-grid">@for(f of fields();track f[0]){<mat-form-field appearance="outline"><mat-label>{{f[1]}}</mat-label><textarea matInput [(ngModel)]="content[f[0]]" [ngModelOptions]="{standalone:true}" rows="3"></textarea></mat-form-field>}</div>
 @if(page==='services'){<h3>Servicios</h3>@for(name of content.serviceName;track $index;let i=$index){<div class="clinical-row"><mat-form-field appearance="outline"><mat-label>Servicio</mat-label><input matInput [(ngModel)]="content.serviceName[i]" [ngModelOptions]="{standalone:true}"></mat-form-field><mat-form-field appearance="outline"><mat-label>Descripción</mat-label><textarea matInput [(ngModel)]="content.serviceDescription[i]" [ngModelOptions]="{standalone:true}"></textarea></mat-form-field><button mat-icon-button type="button" (click)="content.serviceName.splice(i,1);content.serviceDescription.splice(i,1)"><mat-icon>delete_outline</mat-icon></button></div>}<button mat-stroked-button type="button" (click)="content.serviceName.push('');content.serviceDescription.push('')">Agregar servicio</button>}
 @if(page==='about'){<h3>Equipo</h3>@for(name of content.teams;track $index;let i=$index){<div class="clinical-row"><mat-form-field appearance="outline"><mat-label>Nombre</mat-label><input matInput [(ngModel)]="content.teams[i]" [ngModelOptions]="{standalone:true}"></mat-form-field><mat-form-field appearance="outline"><mat-label>Cargo</mat-label><input matInput [(ngModel)]="content.teamPost[i]" [ngModelOptions]="{standalone:true}"></mat-form-field><button mat-icon-button type="button" (click)="content.teams.splice(i,1);content.teamPost.splice(i,1)"><mat-icon>delete_outline</mat-icon></button></div>}<button mat-stroked-button type="button" (click)="content.teams.push('');content.teamPost.push('')">Agregar integrante</button>}
 <app-file-input label="Imágenes públicas" [(value)]="content.images" [multiple]="true" [publish]="true"/>
`})
export class PageFields {
 @Input() page='home';@Input() content:any={};
 definitions:Record<string,string[][]>={home:[['headline','Título principal'],['tagline','Subtítulo'],['welcome','Bienvenida'],['welCol','Descripción de bienvenida'],['caring','Título de atención'],['caringText','Descripción de atención'],['services','Introducción de servicios'],['review','Título de testimonios'],['reviewText','Descripción de testimonios']],about:[['aboutWhyChooseUs','Por qué elegirnos'],['aboutOurTeam','Presentación del equipo'],['aboutWorkHeart','Nuestra forma de trabajar'],['aboutAnnualCheck','Revisiones'],['aboutHelpHand','Atención']],services:[['serviceText','Introducción'],['feature','Características'],['open','Atención'],['work','Trabajo'],['check','Revisiones'],['smile','Sonrisas']],contact:[['contactMail','Correo de contacto'],['contactPhone','Teléfono'],['contactAddress','Dirección']]};
 fields(){for(const key of ['images','serviceName','serviceDescription','teams','teamPost'])if(!Array.isArray(this.content[key]))this.content[key]=[];return this.definitions[this.page]||[];}
}
