import {Component,inject,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {RouterLink,ActivatedRoute} from '@angular/router';
import {takeUntilDestroyed} from '@angular/core/rxjs-interop';
import {Api,errorText} from './api';
import {MATERIAL} from './material';
@Component({standalone:true,imports:[FormsModule,RouterLink,...MATERIAL],template:`
 <div class="public-site"><header class="public-nav"><a routerLink="/sitio/home" class="brand"><span class="brand-mark"><mat-icon>health_and_safety</mat-icon></span>Clínica Dental</a><nav><a routerLink="/sitio/home">Inicio</a><a routerLink="/sitio/about">Nosotros</a><a routerLink="/sitio/services">Servicios</a><a routerLink="/sitio/contact">Contacto</a><a mat-stroked-button routerLink="/dashboard">Ingresar</a></nav></header>
 @if(error()){<div class="error-banner">{{error()}}</div>}@if(loading()){<mat-progress-bar mode="indeterminate"/>}
 @if(page()==='home'){<section class="public-hero"><div><p class="eyebrow">ATENCIÓN DENTAL</p><h1>{{content()['headline']||'Cuidamos de tu sonrisa'}}</h1><p>{{content()['tagline']}}</p><a mat-flat-button href="#reservar">Reservar una cita</a></div><img [src]="image(0)" alt="Clínica dental"></section><section class="public-section"><h2>{{content()['welcome']}}</h2><p>{{content()['welCol']||content()['caringText']}}</p><h2>{{content()['caring']}}</h2></section>}
 @if(page()==='about'){<section class="public-section"><p class="eyebrow">NOSOTROS</p><h1>Conoce nuestra clínica</h1><p>{{content()['aboutWhyChooseUs']}}</p><p>{{content()['aboutWorkHeart']}}</p><h2>Nuestro equipo</h2><p>{{content()['aboutOurTeam']}}</p><div class="public-cards">@for(name of content()['teams']||[];track $index;let i=$index){<article class="panel settings-panel"><h3>{{name}}</h3><p>{{content()['teamPost']?.[i]}}</p></article>}</div><p>{{content()['aboutAnnualCheck']}}</p><p>{{content()['aboutHelpHand']}}</p></section>}
 @if(page()==='services'){<section class="public-section"><p class="eyebrow">SERVICIOS</p><h1>Atención para tu salud bucal</h1><p>{{content()['serviceText']}}</p><div class="public-cards">@for(name of content()['serviceName']||[];track $index;let i=$index){<article class="panel settings-panel"><mat-icon>medical_services</mat-icon><h2>{{name}}</h2><p>{{content()['serviceDescription']?.[i]}}</p></article>}</div><p>{{content()['feature']}}</p><p>{{content()['open']}}</p><p>{{content()['work']}}</p><p>{{content()['check']}}</p><p>{{content()['smile']}}</p></section>}
 @if(page()==='contact'){<section class="public-section"><p class="eyebrow">CONTACTO</p><h1>Conversemos</h1><p>{{content()['contactAddress']}}</p><p>{{content()['contactPhone']}} · {{content()['contactMail']}}</p><form class="panel settings-panel" #contactForm="ngForm" (ngSubmit)="contactForm.valid&&contact()"><div class="form-grid"><mat-form-field appearance="outline"><mat-label>Nombre</mat-label><input matInput name="nombre" [(ngModel)]="message.nombre" required></mat-form-field><mat-form-field appearance="outline"><mat-label>Correo</mat-label><input matInput type="email" name="correo" [(ngModel)]="message.correo" required></mat-form-field><mat-form-field class="full-width" appearance="outline"><mat-label>Mensaje</mat-label><textarea matInput name="mensaje" [(ngModel)]="message.mensaje" required></textarea></mat-form-field></div><button mat-flat-button [disabled]="busy()">Enviar mensaje</button></form></section>}
 @if(page()==='home'){<section class="public-section" id="reservar"><div class="panel settings-panel"><h2>Reserva tu próxima cita</h2><p>Elige un médico y una fecha para ver los horarios disponibles.</p><form #bookingForm="ngForm" (ngSubmit)="bookingForm.valid&&book()"><div class="form-grid"><mat-form-field appearance="outline"><mat-label>Nombre completo</mat-label><input matInput name="nombre" [(ngModel)]="booking.nombre" required></mat-form-field><mat-form-field appearance="outline"><mat-label>Correo electrónico</mat-label><input matInput type="email" name="correo" [(ngModel)]="booking.correo" required></mat-form-field><mat-form-field appearance="outline"><mat-label>Teléfono</mat-label><input matInput name="telefono" [(ngModel)]="booking.telefono" required></mat-form-field><mat-form-field appearance="outline"><mat-label>Médico</mat-label><mat-select name="medico" [(ngModel)]="booking.medico_id" (selectionChange)="availability()" required>@for(d of doctors();track d.id){<mat-option [value]="d.id">{{d.nombre}} · {{d.especialidad||d.departamento}}</mat-option>}</mat-select></mat-form-field><mat-form-field appearance="outline"><mat-label>Fecha</mat-label><input matInput type="date" name="fecha" [(ngModel)]="booking.fecha_cita" (ngModelChange)="availability()" required></mat-form-field><mat-form-field appearance="outline"><mat-label>Hora disponible</mat-label><mat-select name="hora" [(ngModel)]="booking.hora_inicio" required>@for(s of slots();track s.inicio){<mat-option [value]="s.inicio">{{s.inicio}} – {{s.fin}}</mat-option>}</mat-select></mat-form-field><mat-form-field class="full-width" appearance="outline"><mat-label>Motivo de consulta</mat-label><textarea matInput name="motivo" [(ngModel)]="booking.motivo_consulta"></textarea></mat-form-field></div><button mat-flat-button [disabled]="busy()">Confirmar cita</button></form></div></section>}
 @if(success()){<div class="public-section"><div class="info-banner">{{success()}}</div></div>}<footer class="public-footer">Clínica Dental · Atención y cuidado de tu sonrisa</footer></div>
`})
export class PublicSite {
 api=inject(Api);route=inject(ActivatedRoute);page=signal('home');content=signal<Record<string,any>>({});doctors=signal<any[]>([]);slots=signal<any[]>([]);error=signal('');success=signal('');loading=signal(false);busy=signal(false);booking:any={};message:any={};
 constructor(){this.route.paramMap.pipe(takeUntilDestroyed()).subscribe(p=>{this.page.set(p.get('page')||'home');this.error.set('');this.success.set('');this.loading.set(true);this.api.get<any>('/public/pages/'+this.page()).subscribe({next:d=>{this.content.set(d.contenido);this.loading.set(false);},error:e=>{this.error.set(errorText(e));this.loading.set(false);}});if(this.page()==='home')this.api.get<any[]>('/public/doctors').subscribe({next:d=>this.doctors.set(d),error:e=>this.error.set(errorText(e))});});}
 image(i:number){const url=this.content()['images']?.[i];return typeof url==='string'&&(url.startsWith('/api/public/')||url.startsWith('/assets/'))?url:'/assets/images/banner3.jpg';}
 availability(){this.booking.hora_inicio=null;if(!this.booking.medico_id||!this.booking.fecha_cita)return;this.api.get<any[]>('/public/slots',{medico:this.booking.medico_id,fecha:this.booking.fecha_cita}).subscribe({next:d=>this.slots.set(d),error:e=>this.error.set(errorText(e))});}
 book(){this.busy.set(true);this.api.post<any>('/public/book',this.booking).subscribe({next:d=>{this.success.set(d.message);this.booking={};this.slots.set([]);this.busy.set(false);},error:e=>{this.error.set(errorText(e));this.busy.set(false);this.availability();}});}
 contact(){this.busy.set(true);this.api.post('/public/contact',this.message).subscribe({next:()=>{this.success.set('Tu mensaje fue enviado a la clínica.');this.message={};this.busy.set(false);},error:e=>{this.error.set(errorText(e));this.busy.set(false);}});}
}
