import {Component,inject,signal,DestroyRef} from '@angular/core';
import {CommonModule} from '@angular/common';
import {FormsModule} from '@angular/forms';
import {MAT_DIALOG_DATA,MatDialog} from '@angular/material/dialog';
import {Api,errorText} from './api';
import {MATERIAL} from './material';

@Component({standalone:true,imports:[...MATERIAL],template:`<div class="action-dialog"><div class="action-dialog-icon"><mat-icon>{{data.icon}}</mat-icon></div><h2 mat-dialog-title>{{data.title}}</h2><mat-dialog-content><p>{{data.message}}</p><small>{{data.detail}}</small></mat-dialog-content><mat-dialog-actions align="end"><button mat-button [mat-dialog-close]="false">Volver</button><button mat-flat-button class="danger-action" [mat-dialog-close]="true">{{data.confirm}}</button></mat-dialog-actions></div>`})
export class ActionConfirmDialog {
 data=inject<{icon:string;title:string;message:string;detail:string;confirm:string}>(MAT_DIALOG_DATA);
}

@Component({standalone:true,imports:[CommonModule,FormsModule,...MATERIAL],template:`
<div class="page-heading"><div><p class="eyebrow">SAN MARTÍN · CERPAX</p><h1>Radiografías</h1><p>Solicitudes, carga externa y consulta de estudios autorizados.</p></div><button mat-stroked-button (click)="load()">Actualizar</button></div>
@if(error()){<p class="error-banner" role="alert">{{error()}}</p>}@if(message()){<p class="info-banner" role="status">{{message()}}</p>}
<nav class="radio-tabs" aria-label="Secciones de radiografías"><button mat-button (click)="tab='solicitudes'">Solicitudes</button><button mat-button (click)="tab='avisos';notifications()">Notificaciones ({{unread()}})</button>@if(isAdmin()){<button mat-button (click)="tab='asignaciones';assignments()">Asignar pacientes</button>}@if(api.can('radiografias','audit')){<button mat-button (click)="tab='historial';history()">Trazabilidad</button>}</nav>
@if(tab==='solicitudes'){
 @if(api.can('radiografias','create')){<section class="panel radio-panel"><h2>Nueva solicitud</h2><form (ngSubmit)="create()" class="radio-form">
 <mat-form-field appearance="outline"><mat-label>Buscar paciente</mat-label><input matInput name="buscar" [(ngModel)]="search" (ngModelChange)="patients()"></mat-form-field>
 <mat-form-field appearance="outline"><mat-label>Paciente</mat-label><mat-select name="paciente" [(ngModel)]="draft.paciente_id" (selectionChange)="patientSelected()" required>@for(p of people();track p.id){<mat-option [value]="p.id">{{p.label}}</mat-option>}</mat-select></mat-form-field>
 @if(isAdmin()){<mat-form-field appearance="outline"><mat-label>Odontólogo responsable</mat-label><mat-select name="doctor" [(ngModel)]="draft.odontologo_id" required>@for(d of doctors();track d.id){<mat-option [value]="d.id">{{d.label}}</mat-option>}</mat-select></mat-form-field>}
 <mat-form-field appearance="outline"><mat-label>Tipo de estudio</mat-label><input matInput name="tipo" [(ngModel)]="draft.tipo" maxlength="150" required placeholder="Panorámica, periapical…"></mat-form-field>
 <mat-form-field appearance="outline"><mat-label>Indicaciones</mat-label><textarea matInput name="indicaciones" [(ngModel)]="draft.indicaciones" maxlength="2000"></textarea></mat-form-field><button mat-flat-button [disabled]="busy()">Crear solicitud</button></form><p>El paciente debe estar asignado al odontólogo responsable.</p></section>}
 <section class="panel radio-panel"><h2>Solicitudes registradas</h2><div class="radio-form"><mat-form-field appearance="outline"><mat-label>Estado</mat-label><mat-select [(ngModel)]="state" (selectionChange)="page=0;load()"><mat-option value="">Todos</mat-option>@for(s of ['Pendiente','Completada','Cancelada'];track s){<mat-option [value]="s">{{s}}</mat-option>}</mat-select></mat-form-field><mat-form-field appearance="outline"><mat-label>Filtrar paciente</mat-label><mat-select [(ngModel)]="filterPatient" (selectionChange)="page=0;load()"><mat-option value="">Todos</mat-option>@for(p of people();track p.id){<mat-option [value]="p.id">{{p.label}}</mat-option>}</mat-select></mat-form-field></div>
 @for(s of rows();track s.id){<article class="radio-record"><div><strong>#{{s.id}} · {{s.paciente}}</strong><p>{{s.tipo}} · {{s.odontologo}} · {{s.creado_en|date:'dd/MM/yyyy HH:mm'}}</p><p>{{s.indicaciones}}</p><span class="status-chip">{{s.estado}}</span></div><div class="radio-actions">
 @if(s.estado==='Pendiente'&&api.can('radiografias','update')){<button mat-stroked-button (click)="selected=s;accessLink.set(null)">Enlace / QR</button><button mat-button (click)="action(s,'revoke')">Revocar enlace</button><button mat-button (click)="action(s,'cancel')">Cancelar solicitud</button>}
 @if(s.archivo_id){<button mat-flat-button (click)="file(s,false)">Visualizar</button><button mat-button (click)="file(s,true)">Descargar</button>}</div></article>}@empty{<p>No hay solicitudes con estos filtros.</p>}
 <div class="radio-actions"><button mat-button [disabled]="page===0" (click)="page=page-1;load()">Anterior</button><span>Página {{page+1}}</span><button mat-button [disabled]="rows().length<25" (click)="page=page+1;load()">Siguiente</button></div></section>
 @if(selected){<section class="panel radio-panel"><h2>Acceso CERPAX · solicitud #{{selected.id}}</h2><p>Generar otro enlace revoca el anterior. El acceso se consume al completar la carga.</p><mat-form-field appearance="outline"><mat-label>Vigencia en horas</mat-label><input matInput type="number" min="1" max="72" [(ngModel)]="hours"></mat-form-field><button mat-flat-button [disabled]="busy()" (click)="generate()">Generar enlace y QR</button>@if(accessLink();as a){<div class="radio-link"><img [src]="a.qr" alt="QR para cargar la radiografía" width="280" height="280"><div><p>Vence: {{a.vence_en|date:'dd/MM/yyyy HH:mm'}}</p><a [href]="a.url" target="_blank" rel="noreferrer">Abrir página de carga</a><p class="radio-url">{{a.url}}</p><button mat-stroked-button (click)="copy(a.url)">Copiar enlace</button><p>Comparte este acceso solo con CERPAX. Para otro equipo, APP_URL debe ser una dirección accesible desde ese equipo.</p></div></div>}<button mat-button (click)="selected=null;accessLink.set(null)">Cerrar</button></section>}
}
@if(tab==='asignaciones'&&isAdmin()){<section class="panel radio-panel"><h2>Pacientes autorizados por odontólogo</h2><form (ngSubmit)="assign()" class="radio-form"><mat-form-field appearance="outline"><mat-label>Buscar paciente</mat-label><input matInput name="busqueda" [(ngModel)]="search" (ngModelChange)="patients()"></mat-form-field><mat-form-field appearance="outline"><mat-label>Paciente a asignar</mat-label><mat-select name="p" [(ngModel)]="assignment.paciente_id" required>@for(p of people();track p.id){<mat-option [value]="p.id">{{p.label}}</mat-option>}</mat-select></mat-form-field><mat-form-field appearance="outline"><mat-label>Odontólogo autorizado</mat-label><mat-select name="d" [(ngModel)]="assignment.odontologo_id" required>@for(d of doctors();track d.id){<mat-option [value]="d.id">{{d.label}}</mat-option>}</mat-select></mat-form-field><button mat-flat-button [disabled]="busy()">Asignar</button></form>@for(a of assigned();track a.paciente_id+':'+a.odontologo_id){<article class="radio-record"><span>{{a.paciente}} → {{a.odontologo}}</span><button mat-button (click)="unassign(a)">Retirar acceso</button></article>}</section>}
@if(tab==='avisos'){<section class="panel radio-panel"><h2>Notificaciones de carga</h2><p>Las nuevas cargas aparecen aquí. Se actualiza cada 30 segundos.</p>@for(n of notices();track n.id){<article class="radio-record"><div><strong>{{n.leido_en?'Leída':'Nueva'}} · Radiografía recibida</strong><p>{{n.paciente}} · {{n.tipo}} · Solicitud #{{n.solicitud_id}}</p><small>{{n.creado_en|date:'dd/MM/yyyy HH:mm'}}</small></div>@if(!n.leido_en){<button mat-button (click)="mark(n)">Marcar leída</button>}</article>}@empty{<p>No hay notificaciones.</p>}</section>}
@if(tab==='historial'&&api.can('radiografias','audit')){<section class="panel radio-panel"><h2>Trazabilidad</h2><div class="radio-form"><mat-form-field appearance="outline"><mat-label>Paciente del historial</mat-label><mat-select [(ngModel)]="auditPatient"><mat-option value="">Todos</mat-option>@for(p of people();track p.id){<mat-option [value]="p.id">{{p.label}}</mat-option>}</mat-select></mat-form-field><mat-form-field appearance="outline"><mat-label>Desde</mat-label><input matInput type="date" [(ngModel)]="from"></mat-form-field><mat-form-field appearance="outline"><mat-label>Hasta</mat-label><input matInput type="date" [(ngModel)]="to"></mat-form-field><button mat-stroked-button (click)="auditPage=0;history()">Filtrar historial</button></div>@for(e of events();track e.id){<article class="radio-record"><div><strong>{{e.evento}}</strong><p>{{e.paciente}} · {{e.usuario||e.actor}} · Solicitud {{e.solicitud_id||'—'}}</p><small>{{e.creado_en|date:'dd/MM/yyyy HH:mm:ss'}}</small></div></article>}@empty{<p>No hay eventos.</p>}<button mat-button [disabled]="auditPage===0" (click)="auditPage=auditPage-1;history()">Anterior</button><button mat-button [disabled]="events().length<50" (click)="auditPage=auditPage+1;history()">Siguiente</button></section>}
`})
export class Radiography {
 api=inject(Api);dialog=inject(MatDialog);destroy=inject(DestroyRef);error=signal('');message=signal('');busy=signal(false);rows=signal<any[]>([]);people=signal<any[]>([]);doctors=signal<any[]>([]);assigned=signal<any[]>([]);events=signal<any[]>([]);notices=signal<any[]>([]);accessLink=signal<any>(null);
 tab='solicitudes';page=0;state='';filterPatient='';search='';auditPatient='';from='';to='';auditPage=0;hours=24;selected:any=null;draft:any={paciente_id:'',odontologo_id:'',tipo:'',indicaciones:''};assignment:any={paciente_id:'',odontologo_id:''};
 constructor(){this.load();this.patients();this.api.get<any>('/lookups/medicos').subscribe({next:r=>this.doctors.set(r.rows),error:e=>this.error.set(errorText(e))});if(this.isAdmin())this.assignments();this.notifications();const timer=setInterval(()=>this.notifications(),30000);this.destroy.onDestroy(()=>clearInterval(timer));}
 isAdmin(){const u=this.api.session()?.user;return !!u&&(u.bypass||u.roles.includes('Super Admin'));}
 unread(){return this.notices().filter(n=>!n.leido_en).length;}
 load(){this.api.get<any>('/radiographs',{page:this.page,estado:this.state,paciente:this.filterPatient}).subscribe({next:r=>{this.rows.set(r.rows);this.error.set('');},error:e=>this.error.set(errorText(e))});}
 patients(){this.api.get<any>('/lookups/pacientes',{search:this.search}).subscribe({next:r=>this.people.set(r.rows),error:e=>this.error.set(errorText(e))});}
 patientSelected(){const assignment=this.assigned().find(a=>String(a.paciente_id)===String(this.draft.paciente_id));if(assignment){this.draft.odontologo_id=assignment.odontologo_id;this.error.set('');this.message.set(`Odontólogo responsable seleccionado: ${assignment.odontologo}.`);return;}this.draft.odontologo_id='';this.message.set('Este paciente todavía no tiene un odontólogo asignado. Asígnalo antes de crear la solicitud.');}
 send(path:string,body:any,done:()=>void){this.busy.set(true);this.error.set('');this.api.post(path,body).subscribe({next:()=>{this.busy.set(false);done();},error:e=>{this.busy.set(false);this.error.set(errorText(e));}});}
 create(){this.send('/radiographs',this.draft,()=>{this.message.set('Solicitud creada. Ya puedes generar el enlace para CERPAX.');this.draft.tipo='';this.draft.indicaciones='';this.load();});}
 generate(){this.busy.set(true);this.api.post<any>('/radiographs/'+this.selected.id+'/access',{horas:this.hours}).subscribe({next:r=>{this.accessLink.set(r);this.busy.set(false);},error:e=>{this.error.set(errorText(e));this.busy.set(false);}});}
 action(s:any,action:string){const cancelling=action==='cancel';this.confirm({icon:cancelling?'cancel':'link_off',title:cancelling?'¿Cancelar solicitud?':'¿Revocar enlace temporal?',message:cancelling?'La solicitud de radiografía quedará cancelada.':'El enlace o QR actual dejará de funcionar de inmediato.',detail:cancelling?'No podrás generar un nuevo acceso para esta solicitud.':'Podrás generar un nuevo enlace cuando lo necesites.',confirm:cancelling?'Cancelar solicitud':'Revocar enlace'},()=>this.send('/radiographs/'+s.id+'/'+action,{},()=>{this.selected=null;this.accessLink.set(null);this.message.set('Solicitud actualizada.');this.load();}));}
 async copy(url:string){try{await navigator.clipboard.writeText(url);this.message.set('Enlace copiado.');}catch{this.message.set('Selecciona el enlace visible y cópialo.');}}
 file(s:any,download:boolean){const popup=download?null:window.open('about:blank','_blank');this.api.blob('/radiographs/'+s.id+'/file',{download:download?'1':'0'}).subscribe({next:b=>{const url=URL.createObjectURL(b);if(popup)popup.location.href=url;else{const a=document.createElement('a');a.href=url;a.download=s.archivo_nombre||'radiografia';a.click();}setTimeout(()=>URL.revokeObjectURL(url),60000);},error:e=>{popup?.close();this.error.set(errorText(e));}});}
 assignments(){this.api.get<any[]>('/patient-assignments').subscribe({next:r=>this.assigned.set(r),error:e=>this.error.set(errorText(e))});}
 assign(){this.send('/patient-assignments',this.assignment,()=>{this.assignments();this.message.set('Paciente asignado.');});}
 unassign(a:any){this.confirm({icon:'person_remove',title:'¿Retirar acceso al paciente?',message:`${a.odontologo} ya no podrá ver ni solicitar radiografías para ${a.paciente}.`,detail:'Las solicitudes ya registradas se conservan para trazabilidad.',confirm:'Retirar acceso'},()=>this.api.delete('/patient-assignments/'+a.paciente_id+'/'+a.odontologo_id).subscribe({next:()=>{this.assignments();this.message.set('Acceso retirado.');},error:e=>this.error.set(errorText(e))}));}
 confirm(data:{icon:string;title:string;message:string;detail:string;confirm:string},accepted:()=>void){this.dialog.open(ActionConfirmDialog,{data,width:'430px',maxWidth:'92vw',autoFocus:false,restoreFocus:true}).afterClosed().subscribe(result=>{if(result)accepted();});}
 history(){this.api.get<any[]>('/radiography-audit',{paciente:this.auditPatient,desde:this.from,hasta:this.to,page:this.auditPage}).subscribe({next:r=>{this.events.set(r);this.error.set('');},error:e=>this.error.set(errorText(e))});}
 notifications(){this.api.get<any[]>('/radiography-notifications').subscribe({next:r=>this.notices.set(r),error:e=>this.error.set(errorText(e))});}
 mark(n:any){this.send('/radiography-notifications/'+n.id+'/read',{},()=>this.notifications());}
}
