import {Component,inject,signal,DestroyRef} from '@angular/core';
import {CommonModule} from '@angular/common';
import {FormsModule} from '@angular/forms';
import {ActivatedRoute} from '@angular/router';
import {MatTableModule} from '@angular/material/table';
import {MatPaginatorModule,PageEvent} from '@angular/material/paginator';
import {MatDialog,MAT_DIALOG_DATA} from '@angular/material/dialog';
import {MatSnackBar} from '@angular/material/snack-bar';
import {takeUntilDestroyed} from '@angular/core/rxjs-interop';
import {Subscription,firstValueFrom} from 'rxjs';
import {Api,Module,Row,errorText} from './api';
import {MATERIAL} from './material';
import {Editor} from './editor';
import {UserAccess} from './roles';
import {DocumentView} from './document';
import {CampaignView} from './campaign';
@Component({standalone:true,imports:[CommonModule,...MATERIAL],template:`<h2 mat-dialog-title>{{data.module.label}} · #{{data.row.id}}</h2><mat-dialog-content><dl class="detail-list">@for(f of data.module.fields;track f.name){@if(!f.secret){<div><dt>{{f.label}}</dt><dd>{{format(data.row[f.name])}}</dd></div>}}</dl>@if(data.row.items){<h3>Conceptos</h3>@for(i of data.row.items;track i.id){<p>{{i.nombre_cuenta}} · {{i.cantidad}} × {{i.precio}} = {{i.total}}</p>}}</mat-dialog-content><mat-dialog-actions align="end"><button mat-button mat-dialog-close>Cerrar</button><button mat-flat-button (click)="print()"><mat-icon>print</mat-icon>Imprimir</button></mat-dialog-actions>`})
export class Detail {data=inject<{module:Module;row:Row}>(MAT_DIALOG_DATA);format(v:any){return v==null?'—':typeof v==='object'?JSON.stringify(v,null,2):v;}print(){window.print();}}
@Component({standalone:true,imports:[CommonModule,...MATERIAL],template:`<h2 mat-dialog-title>Eliminar registro</h2><mat-dialog-content><p>¿Quieres eliminar este registro de {{data.label.toLowerCase()}}?</p><p>Esta acción modifica los datos de la clínica.</p></mat-dialog-content><mat-dialog-actions align="end"><button mat-button mat-dialog-close>Cancelar</button><button mat-flat-button [mat-dialog-close]="true">Eliminar</button></mat-dialog-actions>`})
export class Confirm {data=inject<{label:string}>(MAT_DIALOG_DATA);}
@Component({standalone:true,imports:[CommonModule,FormsModule,MatTableModule,MatPaginatorModule,...MATERIAL],template:`
  @if(module();as m){<div class="page-heading"><div><p class="eyebrow">{{m.group}}</p><h1>{{m.label}}</h1><p>Administra los registros de tu clínica.</p></div>@if(m.actions?.includes('create')){<button mat-flat-button (click)="edit()"><mat-icon>add</mat-icon>Nuevo registro</button>}</div>
  @if(m.key.startsWith('campanas')){<div class="info-banner">Puedes preparar las campañas. Los mensajes se envían en la fecha programada cuando el procesador está activo. Consulta el seguimiento en cada registro.</div>}
  <section class="panel records-panel"><div class="table-toolbar"><mat-form-field appearance="outline" class="search-field"><mat-icon matPrefix>search</mat-icon><mat-label>Buscar en {{m.label.toLowerCase()}}</mat-label><input matInput [(ngModel)]="search" (input)="searchChanged()"></mat-form-field><div class="table-tools"><span>{{total()}} registros</span><button mat-button (click)="excel()">Excel</button><button mat-icon-button (click)="load()" aria-label="Actualizar"><mat-icon>refresh</mat-icon></button><button mat-stroked-button (click)="exportCsv()" [disabled]="exporting()"><mat-icon>download</mat-icon>{{exporting()?'Exportando…':'Exportar CSV'}}</button></div></div>
  @if(loading()){<mat-progress-bar mode="indeterminate"/>}@if(error()){<div class="error-banner">{{error()}} <button mat-button (click)="load()">Reintentar</button></div>}
  <div class="table-scroll"><table mat-table [dataSource]="rows()">@for(c of columns();track c.name){<ng-container [matColumnDef]="c.name"><th mat-header-cell *matHeaderCellDef>{{c.label}}</th><td mat-cell *matCellDef="let row">@if(c.name==='estado'){<span class="status-chip" [class.inactive]="row[c.name]==='0'">{{display(row[c.name],c.name)}}</span>}@else{<span [title]="display(row[c.name],c.name)">{{display(row[c.name],c.name)}}</span>}</td></ng-container>}
  <ng-container matColumnDef="actions"><th mat-header-cell *matHeaderCellDef>Acciones</th><td mat-cell *matCellDef="let row"><button mat-icon-button (click)="show(row)" aria-label="Ver registro"><mat-icon>visibility</mat-icon></button>@if(m.table==='usuarios'&&api.can('roles')){<button mat-icon-button (click)="access(row)" aria-label="Asignar roles"><mat-icon>admin_panel_settings</mat-icon></button>}@if(m.key.startsWith('campanas-')){<button mat-icon-button (click)="campaign(row)" aria-label="Seguimiento de campaña"><mat-icon>send</mat-icon></button>}@if(m.actions?.includes('update')){<button mat-icon-button (click)="edit(row)" aria-label="Editar registro"><mat-icon>edit</mat-icon></button>}@if(m.actions?.includes('delete')&&!['empresas','aplicacion'].includes(m.key)){<button mat-icon-button (click)="remove(row)" aria-label="Eliminar registro"><mat-icon>delete_outline</mat-icon></button>}</td></ng-container>
  <tr mat-header-row *matHeaderRowDef="columnKeys()"></tr><tr mat-row *matRowDef="let row;columns:columnKeys();"></tr></table></div>
  @if(!loading()&&!error()&&!rows().length){<div class="empty-state"><mat-icon>{{m.icon}}</mat-icon><h3>{{search?'No encontramos coincidencias':'Todavía no hay registros'}}</h3><p>{{search?'Prueba con otra búsqueda.':'Agrega el primer registro para comenzar.'}}</p>@if(!search&&m.actions?.includes('create')){<button mat-stroked-button (click)="edit()">Crear registro</button>}</div>}
  <mat-paginator [length]="total()" [pageIndex]="page" [pageSize]="size" [pageSizeOptions]="[15,30,50]" (page)="paginate($event)" showFirstLastButtons aria-label="Páginas de registros"/>
  </section>}
`})
export class Records {
  access(row:Row){this.dialog.open(UserAccess,{data:{id:row.id},width:'500px'});}
  campaign(row:Row){this.dialog.open(CampaignView,{data:{channel:this.module()!.key.replace('campanas-',''),id:row.id},width:'900px'});}
  excel(){this.api.blob('/export/'+this.module()!.key,{search:this.search}).subscribe({next:b=>{const url=URL.createObjectURL(b);const a=document.createElement('a');a.href=url;a.download=this.module()!.key+'.xlsx';a.click();URL.revokeObjectURL(url);},error:e=>this.notify(e)});}
  api=inject(Api);route=inject(ActivatedRoute);dialog=inject(MatDialog);snack=inject(MatSnackBar);destroy=inject(DestroyRef);
  module=signal<Module|null>(null);rows=signal<Row[]>([]);total=signal(0);loading=signal(true);error=signal('');exporting=signal(false);columns=signal<{name:string;label:string}[]>([]);columnKeys=signal<string[]>([]);search='';page=0;size=15;request?:Subscription;timer?:ReturnType<typeof setTimeout>;
  constructor(){this.route.paramMap.pipe(takeUntilDestroyed()).subscribe(p=>{this.search='';this.page=0;this.api.catalog$.subscribe({next:modules=>{const m=modules.find(m=>m.key===p.get('key'));if(!m)return;this.module.set(m);const fields=m.fields.filter(f=>!f.secret&&!['textarea','json'].includes(f.type));const cols=[{name:'id',label:'#'},...fields.slice(0,6)];this.columns.set(cols);this.columnKeys.set([...cols.map(c=>c.name),'actions']);this.load();},error:e=>{this.error.set(errorText(e));this.loading.set(false);}});});this.destroy.onDestroy(()=>{this.request?.unsubscribe();clearTimeout(this.timer);});}
  load(){const m=this.module();if(!m)return;this.request?.unsubscribe();this.loading.set(true);this.error.set('');this.request=this.api.list(m.key,this.page,this.size,this.search).subscribe({next:d=>{this.rows.set(d.rows);this.total.set(d.total);this.loading.set(false);},error:e=>{this.error.set(errorText(e));this.loading.set(false);}});}
  searchChanged(){clearTimeout(this.timer);this.timer=setTimeout(()=>{this.page=0;this.load();},350);}
  paginate(e:PageEvent){this.page=e.pageIndex;this.size=e.pageSize;this.load();}
  display(value:any,key:string){if(value==null)return '—';if(key==='estado')return ({'1':'Activo','0':'Inactivo',Pending:'Pendiente',Completed:'Completado',Processing:'En proceso',Failed:'Fallido'} as Record<string,string>)[value]||value;if(typeof value==='object')return JSON.stringify(value);if(key.startsWith('fecha'))return String(value).slice(0,10);return String(value);}
  edit(row?:Row){const m=this.module()!;const open=(record?:Row)=>this.dialog.open(Editor,{data:{module:m,row:record},width:'880px',maxWidth:'96vw',disableClose:true}).afterClosed().subscribe(saved=>{if(saved){this.snack.open('Registro guardado','Cerrar',{duration:3000});this.load();}});if(row)this.api.get<Row>('/records/'+m.key+'/'+row.id).subscribe({next:r=>open(r),error:e=>this.notify(e)});else open();}
  show(row:Row){this.api.get<Row>('/records/'+this.module()!.key+'/'+row.id).subscribe({next:r=>this.dialog.open(DocumentView,{data:{module:this.module(),row:r},width:'800px'}),error:e=>this.notify(e)});}
  remove(row:Row){this.dialog.open(Confirm,{data:{label:this.module()!.label},width:'420px'}).afterClosed().subscribe(ok=>{if(ok)this.api.delete('/records/'+this.module()!.key+'/'+row.id).subscribe({next:()=>{this.snack.open('Registro eliminado','Cerrar',{duration:3000});this.load();},error:e=>this.notify(e)});});}
  notify(e:any){this.snack.open(errorText(e),'Cerrar',{duration:7000});}
  async exportCsv(){this.exporting.set(true);try{const m=this.module()!,all:Row[]=[];let page=0,total=1;while(all.length<total){const d=await firstValueFrom(this.api.list(m.key,page++,100,this.search));total=d.total;if(!d.rows.length)break;all.push(...d.rows);}const fields=[{name:'id',label:'ID'},...m.fields.filter(f=>!f.secret)];const escape=(v:any)=>'"'+String(v??'').replace(/^[=+@\-]/,"'$&").replaceAll('"','""')+'"';const csv=[fields.map(f=>escape(f.label)).join(','),...all.map(r=>fields.map(f=>escape(this.display(r[f.name],f.name))).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=m.key+'.csv';a.click();URL.revokeObjectURL(url);}catch(e){this.notify(e);}finally{this.exporting.set(false);}}
}
