import {Component,inject,signal} from '@angular/core';
import {CommonModule} from '@angular/common';
import {FormsModule} from '@angular/forms';
import {MATERIAL} from './material';
import {Api,errorText} from './api';
@Component({standalone:true,imports:[CommonModule,FormsModule,...MATERIAL],template:`<div class="page-heading"><div><p class="eyebrow">FINANZAS</p><h1>Reporte financiero</h1><p>Movimientos de pagos y conceptos de facturas.</p></div><div><button mat-stroked-button (click)="export()"><mat-icon>download</mat-icon>Excel</button><button mat-stroked-button (click)="print()"><mat-icon>print</mat-icon>Imprimir</button></div></div>
 <section class="panel settings-panel"><div class="form-grid"><mat-form-field appearance="outline"><mat-label>Desde</mat-label><input matInput type="date" [(ngModel)]="from"></mat-form-field><mat-form-field appearance="outline"><mat-label>Hasta</mat-label><input matInput type="date" [(ngModel)]="to"></mat-form-field></div><button mat-flat-button (click)="load()">Consultar</button></section>
 <section class="metrics"><article class="metric-card"><span>Créditos</span><strong>{{totals().creditos|number:'1.2-2'}}</strong></article><article class="metric-card"><span>Débitos</span><strong>{{totals().debitos|number:'1.2-2'}}</strong></article><article class="metric-card"><span>Balance</span><strong>{{totals().creditos-totals().debitos|number:'1.2-2'}}</strong></article></section>
 <section class="panel">@if(loading()){<mat-progress-bar mode="indeterminate"/>}@if(error()){<p class="error-banner">{{error()}}</p>}<div class="table-scroll"><table class="report-table"><thead><tr><th>Fecha</th><th>Origen</th><th>Concepto</th><th>Tipo</th><th>Importe</th></tr></thead><tbody>@for(r of rows();track $index){<tr><td>{{r.fecha|date:'dd/MM/yyyy'}}</td><td>{{r.origen}}</td><td>{{r.concepto}}</td><td>{{r.tipo==='Credit'?'Crédito':'Débito'}}</td><td>{{r.importe|number:'1.2-2'}}</td></tr>}</tbody></table></div>@if(!loading()&&!rows().length){<div class="empty-state"><mat-icon>bar_chart</mat-icon><h3>No hay movimientos en este período</h3></div>}</section>`})
export class Reports {api=inject(Api);rows=signal<any[]>([]);totals=signal({creditos:0,debitos:0});loading=signal(false);error=signal('');from='';to='';constructor(){this.load();}load(){this.loading.set(true);this.error.set('');this.api.get<any>('/reports/financial',{from:this.from,to:this.to}).subscribe({next:r=>{this.rows.set(r.rows);this.totals.set(r.totals);this.loading.set(false);},error:e=>{this.error.set(errorText(e));this.loading.set(false);}});}print(){window.print();}export(){this.api.blob('/reports/financial/export',{from:this.from,to:this.to}).subscribe({next:b=>{const url=URL.createObjectURL(b);const a=document.createElement('a');a.href=url;a.download='reporte-financiero.xlsx';a.click();URL.revokeObjectURL(url);},error:e=>this.error.set(errorText(e))});}}
