-- Instalación independiente de Angular + Node.js. Ejecutar en una base VACÍA.
BEGIN;

CREATE TABLE "usuarios" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" BIGINT,
  "nombre" VARCHAR(255) NOT NULL,
  "correo" VARCHAR(255) NOT NULL UNIQUE,
  "correo_verificado_en" TIMESTAMPTZ,
  "contrasena" VARCHAR(255) NOT NULL,
  "telefono" VARCHAR(255),
  "direccion" TEXT,
  "foto" VARCHAR(255),
  "configuracion_regional" VARCHAR(255),
  "fecha_nacimiento" DATE,
  "genero" VARCHAR(255) CHECK ("genero" IN ('male','female')),
  "grupo_sanguineo" VARCHAR(255) CHECK ("grupo_sanguineo" IN ('A+','A-','B+','B-','AB+','AB-','O+','O-')),
  "estado" VARCHAR(255) NOT NULL DEFAULT '0' CHECK ("estado" IN ('0','1')),
  "token_recordatorio" VARCHAR(100),
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ,
  "eliminado_en" TIMESTAMPTZ
);

CREATE TABLE "configuracion_aplicacion" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_aplicacion" VARCHAR(255) NOT NULL,
  "nombre_corto_aplicacion" VARCHAR(255) NOT NULL,
  "version_aplicacion" VARCHAR(255) NOT NULL,
  "nombre_empresa" VARCHAR(255) NOT NULL,
  "correo_empresa" VARCHAR(255),
  "direccion_empresa" TEXT,
  "desarrollado_por" VARCHAR(255),
  "enlace_desarrollador" VARCHAR(255),
  "titulo_desarrollador" VARCHAR(255),
  "prefijo_desarrollador" VARCHAR(255),
  "correo_soporte" VARCHAR(255),
  "logotipo" VARCHAR(255),
  "icono_sitio" VARCHAR(255),
  "idioma" VARCHAR(255),
  "es_demostracion" VARCHAR(255) NOT NULL DEFAULT '0' CHECK ("es_demostracion" IN ('0','1')),
  "zona_horaria" VARCHAR(255) NOT NULL,
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ
);

CREATE TABLE "configuraciones_smtp" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_remitente" VARCHAR(255) NOT NULL,
  "correo_remitente" VARCHAR(255) NOT NULL,
  "servidor_smtp" VARCHAR(255) NOT NULL,
  "puerto_smtp" VARCHAR(255) NOT NULL,
  "usuario_smtp" VARCHAR(255) NOT NULL,
  "tipo_smtp" VARCHAR(255) NOT NULL DEFAULT 'default' CHECK ("tipo_smtp" IN ('default','tls','ssl')),
  "contrasena_smtp" VARCHAR(255) NOT NULL,
  "estado" VARCHAR(255) NOT NULL DEFAULT '1' CHECK ("estado" IN ('1','0')),
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ
);

CREATE TABLE "empresas" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dominio" VARCHAR(255) NOT NULL,
  "habilitado" BOOLEAN NOT NULL DEFAULT true,
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ,
  "eliminado_en" TIMESTAMPTZ
);

CREATE TABLE "configuraciones" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" BIGINT NOT NULL,
  "clave" VARCHAR(255) NOT NULL,
  "valor" TEXT,
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ
);

CREATE TABLE "monedas" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" BIGINT NOT NULL,
  "nombre" VARCHAR(255) NOT NULL,
  "codigo" VARCHAR(255) NOT NULL,
  "tasa" DOUBLE PRECISION NOT NULL,
  "habilitado" SMALLINT NOT NULL DEFAULT 0,
  "precision" VARCHAR(255),
  "simbolo" VARCHAR(255),
  "simbolo_primero" VARCHAR(255),
  "separador_decimal" VARCHAR(255),
  "separador_miles" VARCHAR(255),
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ
);

CREATE TABLE "impuestos" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" BIGINT NOT NULL,
  "nombre" VARCHAR(255) NOT NULL,
  "tasa" DOUBLE PRECISION NOT NULL,
  "habilitado" BOOLEAN NOT NULL,
  "tipo" VARCHAR(255) NOT NULL DEFAULT 'normal',
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ
);

CREATE TABLE "usuarios_empresas" (
  "usuario_id" BIGINT NOT NULL,
  "empresa_id" BIGINT NOT NULL,
  "tipo_usuario" VARCHAR(255) NOT NULL,
  PRIMARY KEY(usuario_id,empresa_id,tipo_usuario)
);

CREATE TABLE "detalles_medicos" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "departamento_hospitalario_id" BIGINT NOT NULL,
  "usuario_id" BIGINT NOT NULL,
  "especialidad" VARCHAR(255),
  "cargo" VARCHAR(255),
  "biografia" TEXT,
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ
);

CREATE TABLE "departamentos_hospitalarios" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" BIGINT NOT NULL,
  "nombre" VARCHAR(255) NOT NULL UNIQUE,
  "descripcion" TEXT,
  "estado" VARCHAR(255) NOT NULL DEFAULT '1' CHECK ("estado" IN ('0','1')),
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ,
  "eliminado_en" TIMESTAMPTZ
);

CREATE TABLE "antecedentes_pacientes" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" BIGINT NOT NULL,
  "alergia_alimentaria" VARCHAR(255),
  "enfermedad_cardiaca" VARCHAR(255),
  "hipertension" VARCHAR(255),
  "diabetes" VARCHAR(255),
  "cirugias" VARCHAR(255),
  "accidentes" VARCHAR(255),
  "otros" VARCHAR(255),
  "antecedentes_familiares" VARCHAR(255),
  "medicacion_actual" VARCHAR(255),
  "embarazo" VARCHAR(255),
  "lactancia" VARCHAR(255),
  "seguro_salud" VARCHAR(255),
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ,
  "archivo" VARCHAR(255)
);

CREATE TABLE "horarios_medicos" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" BIGINT NOT NULL,
  "dia_semana" VARCHAR(255) NOT NULL CHECK ("dia_semana" IN ('Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday')),
  "hora_inicio" TIME NOT NULL,
  "hora_fin" TIME NOT NULL,
  "duracion_media_cita" INTEGER NOT NULL DEFAULT 5,
  "tipo_turno" VARCHAR(255) NOT NULL DEFAULT 'Sequential' CHECK ("tipo_turno" IN ('Sequential','Timestamp')),
  "estado" VARCHAR(255) NOT NULL CHECK ("estado" IN ('0','1')),
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ
);

CREATE TABLE "citas_pacientes" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" BIGINT NOT NULL,
  "medico_id" BIGINT NOT NULL,
  "numero_turno" INTEGER NOT NULL,
  "hora_inicio" TIME NOT NULL,
  "hora_fin" TIME NOT NULL,
  "fecha_cita" DATE NOT NULL,
  "motivo_consulta" TEXT,
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ,
  "empresa_id" BIGINT DEFAULT '1'
);

CREATE TABLE "informes_laboratorio" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" BIGINT NOT NULL,
  "fecha" DATE NOT NULL,
  "paciente_id" BIGINT NOT NULL,
  "medico_id" BIGINT,
  "plantilla_informe_laboratorio_id" BIGINT,
  "informe" TEXT NOT NULL,
  "foto" JSONB,
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ
);

CREATE TABLE "plantillas_informes_laboratorio" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" BIGINT,
  "nombre" VARCHAR(255) NOT NULL UNIQUE,
  "plantilla" TEXT NOT NULL,
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ
);

CREATE TABLE "recetas" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" BIGINT NOT NULL,
  "medico_id" BIGINT NOT NULL,
  "peso" DOUBLE PRECISION,
  "estatura" DOUBLE PRECISION,
  "presion_arterial" VARCHAR(255),
  "sintoma_principal" TEXT,
  "informacion_medicamentos" JSONB,
  "informacion_diagnosticos" JSONB,
  "nota" TEXT,
  "fecha_receta" DATE NOT NULL,
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ
);

CREATE TABLE "seguros" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" BIGINT NOT NULL,
  "nombre" VARCHAR(255) NOT NULL UNIQUE,
  "impuesto_servicio" DOUBLE PRECISION DEFAULT 0,
  "descuento" DOUBLE PRECISION DEFAULT 0,
  "descripcion" TEXT,
  "numero_seguro" VARCHAR(255),
  "codigo_seguro" VARCHAR(255),
  "cargos_enfermedades" JSONB,
  "tarifa_hospital" DOUBLE PRECISION DEFAULT 0,
  "tarifa_seguro" DOUBLE PRECISION DEFAULT 0,
  "total" DOUBLE PRECISION DEFAULT 0,
  "estado" VARCHAR(255) NOT NULL DEFAULT '1' CHECK ("estado" IN ('1','0')),
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ
);

CREATE TABLE "cuentas_contables" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" BIGINT NOT NULL,
  "nombre" VARCHAR(255) NOT NULL,
  "tipo" VARCHAR(255) NOT NULL CHECK ("tipo" IN ('Debit','Credit')),
  "descripcion" TEXT,
  "estado" VARCHAR(255) NOT NULL DEFAULT '1' CHECK ("estado" IN ('1','0')),
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ,
  "eliminado_en" TIMESTAMPTZ
);

CREATE TABLE "proveedores_sms" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" BIGINT NOT NULL,
  "pasarela" VARCHAR(255) NOT NULL CHECK ("pasarela" IN ('twilio','nexmo','plivo','clickatell')),
  "autenticacion_id" VARCHAR(255),
  "token_autenticacion" VARCHAR(255),
  "api_id" VARCHAR(255),
  "numero_remitente" VARCHAR(255),
  "estado" VARCHAR(255) NOT NULL DEFAULT '0' CHECK ("estado" IN ('1','0')),
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ
);

CREATE TABLE "pagos" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" BIGINT NOT NULL,
  "nombre_cuenta" VARCHAR(255) NOT NULL,
  "tipo_cuenta" VARCHAR(255) NOT NULL CHECK ("tipo_cuenta" IN ('Credit','Debit')),
  "fecha_pago" DATE NOT NULL,
  "nombre_receptor" VARCHAR(255) NOT NULL,
  "descripcion" TEXT,
  "importe" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ
);

CREATE TABLE "plantillas_sms" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" BIGINT,
  "nombre" VARCHAR(255) NOT NULL UNIQUE,
  "plantilla" TEXT NOT NULL,
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ
);

CREATE TABLE "facturas" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" BIGINT NOT NULL,
  "usuario_id" BIGINT NOT NULL,
  "seguro_id" BIGINT,
  "fecha_factura" DATE NOT NULL,
  "total" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "porcentaje_iva" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "total_iva" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "porcentaje_descuento" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "total_descuento" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "total_general" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "pagado" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "saldo_pendiente" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ
);

CREATE TABLE "detalles_facturas" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" BIGINT NOT NULL,
  "factura_id" BIGINT NOT NULL,
  "nombre_cuenta" VARCHAR(255) NOT NULL,
  "descripcion" TEXT,
  "tipo_cuenta" VARCHAR(255) NOT NULL CHECK ("tipo_cuenta" IN ('Debit','Credit')),
  "cantidad" INTEGER NOT NULL,
  "precio" DOUBLE PRECISION NOT NULL,
  "total" DOUBLE PRECISION NOT NULL,
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ
);

CREATE TABLE "campanas_sms" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" BIGINT,
  "nombre_campana" VARCHAR(255) NOT NULL,
  "plantilla_sms_id" BIGINT,
  "mensaje" TEXT NOT NULL,
  "fecha_programada" TIMESTAMPTZ NOT NULL,
  "tipo_contacto" VARCHAR(255) NOT NULL,
  "estado" VARCHAR(255) NOT NULL DEFAULT 'Pending' CHECK ("estado" IN ('Pending','Processing','Completed','Failed')),
  "eliminado_en" TIMESTAMPTZ,
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ
);

CREATE TABLE "registros_campanas_sms" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" BIGINT NOT NULL,
  "campana_sms_id" BIGINT NOT NULL,
  "proveedor_sms_id" BIGINT NOT NULL,
  "entrega_id" VARCHAR(255),
  "estado" VARCHAR(255) NOT NULL CHECK ("estado" IN ('0','1')),
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ
);

CREATE TABLE "plantillas_correo" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" BIGINT,
  "nombre" VARCHAR(255) NOT NULL UNIQUE,
  "plantilla" TEXT NOT NULL,
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ
);

CREATE TABLE "campanas_correo" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" BIGINT,
  "nombre_campana" VARCHAR(255) NOT NULL,
  "plantilla_correo_id" BIGINT,
  "mensaje" TEXT NOT NULL,
  "fecha_programada" TIMESTAMPTZ NOT NULL,
  "tipo_contacto" VARCHAR(255) NOT NULL,
  "estado" VARCHAR(255) NOT NULL DEFAULT 'Pending' CHECK ("estado" IN ('Pending','Processing','Completed','Failed')),
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ
);

CREATE TABLE "registros_campanas_correo" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" BIGINT NOT NULL,
  "campana_correo_id" BIGINT NOT NULL,
  "configuracion_smtp_id" BIGINT NOT NULL,
  "estado" VARCHAR(255) NOT NULL CHECK ("estado" IN ('0','1')),
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ
);

CREATE TABLE "paginas_publicas" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pagina" VARCHAR(255) NOT NULL UNIQUE,
  "contenido" JSONB NOT NULL,
  "estado" VARCHAR(255) NOT NULL DEFAULT '1' CHECK ("estado" IN ('0','1')),
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ
);

CREATE TABLE "mensajes_contacto" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" VARCHAR(255) NOT NULL,
  "correo" VARCHAR(255) NOT NULL,
  "mensaje" TEXT NOT NULL,
  "creado_en" TIMESTAMPTZ,
  "actualizado_en" TIMESTAMPTZ
);

CREATE TABLE "roles" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL UNIQUE,
  nombre_guardia VARCHAR(255) NOT NULL DEFAULT 'web',
  es_predeterminado VARCHAR(1) NOT NULL DEFAULT '0',
  destino_rol VARCHAR(1) NOT NULL DEFAULT '1',
  precio VARCHAR(255),
  vigencia VARCHAR(255),
  creado_en TIMESTAMPTZ,
  actualizado_en TIMESTAMPTZ
);

CREATE TABLE "permisos" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL UNIQUE,
  nombre_visible VARCHAR(255) NOT NULL,
  nombre_guardia VARCHAR(255) NOT NULL DEFAULT 'web'
);

CREATE TABLE "roles_modelos" (
  rol_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  tipo_modelo TEXT NOT NULL DEFAULT 'User',
  modelo_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  PRIMARY KEY(rol_id,tipo_modelo,modelo_id)
);

CREATE TABLE "permisos_roles" (
  permiso_id BIGINT NOT NULL REFERENCES permisos(id) ON DELETE CASCADE,
  rol_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  PRIMARY KEY(permiso_id,rol_id)
);

CREATE TABLE "permisos_modelos" (
  permiso_id BIGINT NOT NULL REFERENCES permisos(id) ON DELETE CASCADE,
  tipo_modelo TEXT NOT NULL DEFAULT 'User',
  modelo_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  PRIMARY KEY(permiso_id,tipo_modelo,modelo_id)
);

CREATE TABLE "archivos" (
  id UUID PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresas(id),
  usuario_id BIGINT NOT NULL REFERENCES usuarios(id),
  nombre TEXT NOT NULL,
  tipo TEXT NOT NULL,
  tamano INTEGER NOT NULL,
  publico BOOLEAN NOT NULL DEFAULT false,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "sesiones_revocadas" (
  token_id UUID PRIMARY KEY,
  expira_en TIMESTAMPTZ NOT NULL
);

CREATE TABLE "restablecimientos_contrasena" (
  correo TEXT PRIMARY KEY,
  token TEXT NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "entregas_campanas" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  canal TEXT NOT NULL CHECK(canal IN ('correo','sms')),
  campana_id BIGINT NOT NULL,
  usuario_id BIGINT NOT NULL REFERENCES usuarios(id),
  empresa_id BIGINT NOT NULL REFERENCES empresas(id),
  estado TEXT NOT NULL DEFAULT 'Pending' CHECK(estado IN ('Pending','Sending','Sent','Failed','Unknown')),
  intentos INTEGER NOT NULL DEFAULT 0,
  proveedor_id BIGINT,
  entrega_id TEXT,
  error TEXT,
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(canal,campana_id,usuario_id)
);

ALTER TABLE usuarios ADD COLUMN version_sesion INTEGER NOT NULL DEFAULT 0;
ALTER TABLE configuraciones_smtp ADD COLUMN empresa_id BIGINT NOT NULL REFERENCES empresas(id);
ALTER TABLE paginas_publicas ADD COLUMN empresa_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE mensajes_contacto ADD COLUMN empresa_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE campanas_correo ADD COLUMN iniciado_en TIMESTAMPTZ;
ALTER TABLE campanas_sms ADD COLUMN iniciado_en TIMESTAMPTZ;
CREATE UNIQUE INDEX un_config_empresa ON configuraciones(empresa_id,clave);
CREATE UNIQUE INDEX un_medico_usuario ON detalles_medicos(usuario_id);
CREATE UNIQUE INDEX un_antecedente_usuario ON antecedentes_pacientes(usuario_id);
CREATE INDEX citas_agenda ON citas_pacientes(medico_id,fecha_cita,hora_inicio);
CREATE INDEX entregas_pendientes ON entregas_campanas(estado,actualizado_en);
CREATE INDEX "idx_usuarios_empresa" ON "usuarios"(empresa_id);
ALTER TABLE "usuarios" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "configuracion_aplicacion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "configuraciones_smtp" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "empresas" ENABLE ROW LEVEL SECURITY;
CREATE INDEX "idx_configuraciones_empresa" ON "configuraciones"(empresa_id);
ALTER TABLE "configuraciones" ENABLE ROW LEVEL SECURITY;
CREATE INDEX "idx_monedas_empresa" ON "monedas"(empresa_id);
ALTER TABLE "monedas" ENABLE ROW LEVEL SECURITY;
CREATE INDEX "idx_impuestos_empresa" ON "impuestos"(empresa_id);
ALTER TABLE "impuestos" ENABLE ROW LEVEL SECURITY;
CREATE INDEX "idx_usuarios_empresas_empresa" ON "usuarios_empresas"(empresa_id);
ALTER TABLE "usuarios_empresas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "detalles_medicos" ENABLE ROW LEVEL SECURITY;
CREATE INDEX "idx_departamentos_hospitalarios_empresa" ON "departamentos_hospitalarios"(empresa_id);
ALTER TABLE "departamentos_hospitalarios" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "antecedentes_pacientes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "horarios_medicos" ENABLE ROW LEVEL SECURITY;
CREATE INDEX "idx_citas_pacientes_empresa" ON "citas_pacientes"(empresa_id);
ALTER TABLE "citas_pacientes" ENABLE ROW LEVEL SECURITY;
CREATE INDEX "idx_informes_laboratorio_empresa" ON "informes_laboratorio"(empresa_id);
ALTER TABLE "informes_laboratorio" ENABLE ROW LEVEL SECURITY;
CREATE INDEX "idx_plantillas_informes_laboratorio_empresa" ON "plantillas_informes_laboratorio"(empresa_id);
ALTER TABLE "plantillas_informes_laboratorio" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "recetas" ENABLE ROW LEVEL SECURITY;
CREATE INDEX "idx_seguros_empresa" ON "seguros"(empresa_id);
ALTER TABLE "seguros" ENABLE ROW LEVEL SECURITY;
CREATE INDEX "idx_cuentas_contables_empresa" ON "cuentas_contables"(empresa_id);
ALTER TABLE "cuentas_contables" ENABLE ROW LEVEL SECURITY;
CREATE INDEX "idx_proveedores_sms_empresa" ON "proveedores_sms"(empresa_id);
ALTER TABLE "proveedores_sms" ENABLE ROW LEVEL SECURITY;
CREATE INDEX "idx_pagos_empresa" ON "pagos"(empresa_id);
ALTER TABLE "pagos" ENABLE ROW LEVEL SECURITY;
CREATE INDEX "idx_plantillas_sms_empresa" ON "plantillas_sms"(empresa_id);
ALTER TABLE "plantillas_sms" ENABLE ROW LEVEL SECURITY;
CREATE INDEX "idx_facturas_empresa" ON "facturas"(empresa_id);
ALTER TABLE "facturas" ENABLE ROW LEVEL SECURITY;
CREATE INDEX "idx_detalles_facturas_empresa" ON "detalles_facturas"(empresa_id);
ALTER TABLE "detalles_facturas" ENABLE ROW LEVEL SECURITY;
CREATE INDEX "idx_campanas_sms_empresa" ON "campanas_sms"(empresa_id);
ALTER TABLE "campanas_sms" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "registros_campanas_sms" ENABLE ROW LEVEL SECURITY;
CREATE INDEX "idx_plantillas_correo_empresa" ON "plantillas_correo"(empresa_id);
ALTER TABLE "plantillas_correo" ENABLE ROW LEVEL SECURITY;
CREATE INDEX "idx_campanas_correo_empresa" ON "campanas_correo"(empresa_id);
ALTER TABLE "campanas_correo" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "registros_campanas_correo" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "paginas_publicas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "mensajes_contacto" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "roles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "permisos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "roles_modelos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "permisos_roles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "permisos_modelos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "archivos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sesiones_revocadas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "restablecimientos_contrasena" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "entregas_campanas" ENABLE ROW LEVEL SECURITY;
COMMIT;
-- Conecta Node con un usuario de servidor propietario de estas tablas.
-- No se crean políticas públicas: el navegador accede exclusivamente a la API.
