-- Datos iniciales de una instalación NUEVA. No contiene pacientes ni contraseñas.
BEGIN;
INSERT INTO empresas(dominio,habilitado) VALUES('localhost',true);
INSERT INTO configuracion_aplicacion(nombre_aplicacion,nombre_corto_aplicacion,version_aplicacion,nombre_empresa,idioma,zona_horaria) VALUES('Clínica Dental','Clínica','2.0.0','Clínica Dental','es','America/La_Paz');
INSERT INTO configuraciones(empresa_id,clave,valor) VALUES(1,'general.company_name','Clínica Dental');
INSERT INTO configuraciones(empresa_id,clave,valor) VALUES(1,'general.company_email','');
INSERT INTO configuraciones(empresa_id,clave,valor) VALUES(1,'general.company_address','');
INSERT INTO configuraciones(empresa_id,clave,valor) VALUES(1,'general.company_phone','');
INSERT INTO configuraciones(empresa_id,clave,valor) VALUES(1,'general.company_tax_number','');
INSERT INTO configuraciones(empresa_id,clave,valor) VALUES(1,'general.company_logo','');
INSERT INTO configuraciones(empresa_id,clave,valor) VALUES(1,'general.default_locale','es');
INSERT INTO configuraciones(empresa_id,clave,valor) VALUES(1,'general.timezone','America/La_Paz');
INSERT INTO configuraciones(empresa_id,clave,valor) VALUES(1,'general.date_format','d-m-Y');
INSERT INTO configuraciones(empresa_id,clave,valor) VALUES(1,'general.financial_start','01-01');
INSERT INTO configuraciones(empresa_id,clave,valor) VALUES(1,'general.default_currency','BOB');
INSERT INTO configuraciones(empresa_id,clave,valor) VALUES(1,'general.default_payment_method','Efectivo');
INSERT INTO configuraciones(empresa_id,clave,valor) VALUES(1,'invoice.prefix','FAC-');
INSERT INTO configuraciones(empresa_id,clave,valor) VALUES(1,'invoice.footer','Gracias por su visita');
INSERT INTO configuraciones(empresa_id,clave,valor) VALUES(1,'invoice.due_date','0');
INSERT INTO configuraciones(empresa_id,clave,valor) VALUES(1,'default.currency','BOB');
INSERT INTO configuraciones(empresa_id,clave,valor) VALUES(1,'default.payment_method','Efectivo');
INSERT INTO monedas(empresa_id,nombre,codigo,tasa,habilitado,precision,simbolo,simbolo_primero,separador_decimal,separador_miles) VALUES(1,'Boliviano','BOB',1,1,'2','Bs','1','.',',');
INSERT INTO roles(nombre,es_predeterminado) VALUES('Super Admin','1');
INSERT INTO roles(nombre,es_predeterminado) VALUES('Doctor','1');
INSERT INTO roles(nombre,es_predeterminado) VALUES('Patient','1');
INSERT INTO roles(nombre,es_predeterminado) VALUES('Accountant','1');
INSERT INTO roles(nombre,es_predeterminado) VALUES('Laboratorist','1');
INSERT INTO roles(nombre,es_predeterminado) VALUES('Receptionist','1');
INSERT INTO permisos(nombre,nombre_visible) VALUES('medicos.read','Médicos · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('medicos.create','Médicos · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('medicos.update','Médicos · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('medicos.delete','Médicos · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('pacientes.read','Pacientes · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('pacientes.create','Pacientes · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('pacientes.update','Pacientes · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('pacientes.delete','Pacientes · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('departamentos.read','Departamentos · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('departamentos.create','Departamentos · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('departamentos.update','Departamentos · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('departamentos.delete','Departamentos · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('horarios.read','Horarios médicos · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('horarios.create','Horarios médicos · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('horarios.update','Horarios médicos · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('horarios.delete','Horarios médicos · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('citas.read','Citas · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('citas.create','Citas · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('citas.update','Citas · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('citas.delete','Citas · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('antecedentes.read','Antecedentes clínicos · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('antecedentes.create','Antecedentes clínicos · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('antecedentes.update','Antecedentes clínicos · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('antecedentes.delete','Antecedentes clínicos · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('recetas.read','Recetas · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('recetas.create','Recetas · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('recetas.update','Recetas · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('recetas.delete','Recetas · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('informes.read','Informes de laboratorio · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('informes.create','Informes de laboratorio · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('informes.update','Informes de laboratorio · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('informes.delete','Informes de laboratorio · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('plantillas-laboratorio.read','Plantillas de informes · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('plantillas-laboratorio.create','Plantillas de informes · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('plantillas-laboratorio.update','Plantillas de informes · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('plantillas-laboratorio.delete','Plantillas de informes · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('seguros.read','Seguros · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('seguros.create','Seguros · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('seguros.update','Seguros · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('seguros.delete','Seguros · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('facturas.read','Facturas · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('facturas.create','Facturas · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('facturas.update','Facturas · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('facturas.delete','Facturas · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('pagos.read','Pagos · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('pagos.create','Pagos · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('pagos.update','Pagos · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('pagos.delete','Pagos · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('cuentas.read','Cuentas contables · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('cuentas.create','Cuentas contables · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('cuentas.update','Cuentas contables · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('cuentas.delete','Cuentas contables · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('monedas.read','Monedas · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('monedas.create','Monedas · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('monedas.update','Monedas · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('monedas.delete','Monedas · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('impuestos.read','Impuestos · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('impuestos.create','Impuestos · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('impuestos.update','Impuestos · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('impuestos.delete','Impuestos · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('paginas.read','Páginas del sitio · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('paginas.create','Páginas del sitio · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('paginas.update','Páginas del sitio · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('paginas.delete','Páginas del sitio · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('contactos.read','Mensajes recibidos · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('contactos.create','Mensajes recibidos · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('contactos.update','Mensajes recibidos · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('contactos.delete','Mensajes recibidos · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('plantillas-correo.read','Plantillas de correo · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('plantillas-correo.create','Plantillas de correo · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('plantillas-correo.update','Plantillas de correo · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('plantillas-correo.delete','Plantillas de correo · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('campanas-correo.read','Campañas de correo · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('campanas-correo.create','Campañas de correo · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('campanas-correo.update','Campañas de correo · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('campanas-correo.delete','Campañas de correo · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('plantillas-sms.read','Plantillas SMS · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('plantillas-sms.create','Plantillas SMS · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('plantillas-sms.update','Plantillas SMS · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('plantillas-sms.delete','Plantillas SMS · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('campanas-sms.read','Campañas SMS · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('campanas-sms.create','Campañas SMS · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('campanas-sms.update','Campañas SMS · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('campanas-sms.delete','Campañas SMS · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('proveedores-sms.read','Proveedores SMS · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('proveedores-sms.create','Proveedores SMS · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('proveedores-sms.update','Proveedores SMS · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('proveedores-sms.delete','Proveedores SMS · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('smtp.read','Servidor de correo · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('smtp.create','Servidor de correo · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('smtp.update','Servidor de correo · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('smtp.delete','Servidor de correo · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('usuarios.read','Usuarios · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('usuarios.create','Usuarios · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('usuarios.update','Usuarios · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('usuarios.delete','Usuarios · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('empresas.read','Empresas · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('empresas.create','Empresas · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('empresas.update','Empresas · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('empresas.delete','Empresas · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('ajustes.read','Ajustes de empresa · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('ajustes.create','Ajustes de empresa · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('ajustes.update','Ajustes de empresa · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('ajustes.delete','Ajustes de empresa · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('aplicacion.read','Aplicación · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('aplicacion.create','Aplicación · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('aplicacion.update','Aplicación · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('aplicacion.delete','Aplicación · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('reportes.read','Reportes · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('reportes.create','Reportes · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('reportes.update','Reportes · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('reportes.delete','Reportes · delete');
INSERT INTO permisos(nombre,nombre_visible) VALUES('roles.read','Roles · read');
INSERT INTO permisos(nombre,nombre_visible) VALUES('roles.create','Roles · create');
INSERT INTO permisos(nombre,nombre_visible) VALUES('roles.update','Roles · update');
INSERT INTO permisos(nombre,nombre_visible) VALUES('roles.delete','Roles · delete');
INSERT INTO permisos_roles(rol_id,permiso_id) SELECT r.id,p.id FROM roles r CROSS JOIN permisos p WHERE r.nombre='Super Admin';
INSERT INTO permisos_roles(rol_id,permiso_id) SELECT r.id,p.id FROM roles r CROSS JOIN permisos p WHERE r.nombre='Doctor' AND p.nombre IN ('recetas.read','recetas.create','recetas.update','recetas.delete','antecedentes.read','antecedentes.create','antecedentes.update','antecedentes.delete','pacientes.read','medicos.read','horarios.read','citas.read','informes.read');
INSERT INTO permisos_roles(rol_id,permiso_id) SELECT r.id,p.id FROM roles r CROSS JOIN permisos p WHERE r.nombre='Patient' AND p.nombre IN ('medicos.read','pacientes.read','antecedentes.read','seguros.read','informes.read','horarios.read','citas.read','recetas.read','facturas.read');
INSERT INTO permisos_roles(rol_id,permiso_id) SELECT r.id,p.id FROM roles r CROSS JOIN permisos p WHERE r.nombre='Accountant' AND p.nombre IN ('cuentas.read','cuentas.create','cuentas.update','cuentas.delete','facturas.read','facturas.create','facturas.update','facturas.delete','pagos.read','pagos.create','pagos.update','pagos.delete','reportes.read','pacientes.read','seguros.read','monedas.read','impuestos.read');
INSERT INTO permisos_roles(rol_id,permiso_id) SELECT r.id,p.id FROM roles r CROSS JOIN permisos p WHERE r.nombre='Laboratorist' AND p.nombre IN ('informes.read','informes.create','informes.update','informes.delete','plantillas-laboratorio.read','plantillas-laboratorio.create','plantillas-laboratorio.update','plantillas-laboratorio.delete','medicos.read','pacientes.read','antecedentes.read');
INSERT INTO permisos_roles(rol_id,permiso_id) SELECT r.id,p.id FROM roles r CROSS JOIN permisos p WHERE r.nombre='Receptionist' AND p.nombre IN ('pacientes.read','pacientes.create','pacientes.update','pacientes.delete','antecedentes.read','antecedentes.create','antecedentes.update','antecedentes.delete','horarios.read','horarios.create','horarios.update','horarios.delete','citas.read','citas.create','citas.update','citas.delete','medicos.read','informes.read','recetas.read');
INSERT INTO paginas_publicas(pagina,contenido,empresa_id) VALUES('home','{"headline":"Cuidamos de tu sonrisa","tagline":"Atención dental cercana y personalizada.","welcome":"Bienvenido a nuestra clínica","caring":"Tu salud bucal, nuestra prioridad","caringText":"Conoce nuestros servicios y reserva tu próxima consulta."}'::jsonb,1);
INSERT INTO paginas_publicas(pagina,contenido,empresa_id) VALUES('about','{"aboutWhyChooseUs":"Atención personalizada para cada paciente.","aboutOurTeam":"Un equipo comprometido con tu salud.","aboutWorkHeart":"Trabajamos con dedicación y cuidado."}'::jsonb,1);
INSERT INTO paginas_publicas(pagina,contenido,empresa_id) VALUES('services','{"serviceName":["Consulta dental","Prevención","Tratamientos"],"serviceDescription":["Evaluación de tu salud bucal.","Limpieza y recomendaciones para cuidar tu sonrisa.","Plan de atención según tus necesidades."]}'::jsonb,1);
INSERT INTO paginas_publicas(pagina,contenido,empresa_id) VALUES('contact','{"contactMail":"","contactPhone":"","contactAddress":""}'::jsonb,1);
COMMIT;
