-- Flujo San Martín / CERPAX. No modifica ni elimina los registros existentes.
CREATE TABLE pacientes_odontologos (
 empresa_id BIGINT NOT NULL REFERENCES empresas(id),
 paciente_id BIGINT NOT NULL REFERENCES usuarios(id),
 odontologo_id BIGINT NOT NULL REFERENCES usuarios(id),
 creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
 PRIMARY KEY(empresa_id,paciente_id,odontologo_id)
);
CREATE TABLE solicitudes_radiografias (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 empresa_id BIGINT NOT NULL REFERENCES empresas(id),
 paciente_id BIGINT NOT NULL REFERENCES usuarios(id),
 odontologo_id BIGINT NOT NULL REFERENCES usuarios(id),
 tipo VARCHAR(150) NOT NULL,
 indicaciones VARCHAR(2000) NOT NULL DEFAULT '',
 estado TEXT NOT NULL DEFAULT 'Pendiente' CHECK(estado IN ('Pendiente','Completada','Cancelada')),
 creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
 completado_en TIMESTAMPTZ
);
CREATE TABLE accesos_radiografias (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 solicitud_id BIGINT NOT NULL REFERENCES solicitudes_radiografias(id),
 token_hash TEXT NOT NULL UNIQUE,
 vence_en TIMESTAMPTZ NOT NULL,
 revocado_en TIMESTAMPTZ,
 usado_en TIMESTAMPTZ,
 creado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE radiografias (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 solicitud_id BIGINT NOT NULL UNIQUE REFERENCES solicitudes_radiografias(id),
 nombre VARCHAR(255) NOT NULL,
 tipo TEXT NOT NULL CHECK(tipo IN ('application/pdf','image/png','image/jpeg','image/webp')),
 tamano INTEGER NOT NULL CHECK(tamano>0 AND tamano<=10485760),
 contenido BYTEA NOT NULL,
 sha256 TEXT NOT NULL,
 creado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE eventos_radiografias (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 empresa_id BIGINT NOT NULL REFERENCES empresas(id),
 solicitud_id BIGINT REFERENCES solicitudes_radiografias(id),
 paciente_id BIGINT NOT NULL REFERENCES usuarios(id),
 usuario_id BIGINT REFERENCES usuarios(id),
 actor TEXT NOT NULL,
 evento TEXT NOT NULL,
 creado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE notificaciones_radiografias (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 solicitud_id BIGINT NOT NULL REFERENCES solicitudes_radiografias(id),
 usuario_id BIGINT NOT NULL REFERENCES usuarios(id),
 creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
 leido_en TIMESTAMPTZ,
 UNIQUE(solicitud_id,usuario_id)
);
CREATE INDEX idx_solicitudes_empresa_paciente ON solicitudes_radiografias(empresa_id,paciente_id,creado_en DESC);
CREATE INDEX idx_asignaciones_odontologo ON pacientes_odontologos(empresa_id,odontologo_id,paciente_id);
CREATE INDEX idx_eventos_empresa_fecha ON eventos_radiografias(empresa_id,creado_en DESC);
CREATE INDEX idx_accesos_solicitud ON accesos_radiografias(solicitud_id);
ALTER TABLE pacientes_odontologos ENABLE ROW LEVEL SECURITY;
ALTER TABLE solicitudes_radiografias ENABLE ROW LEVEL SECURITY;
ALTER TABLE accesos_radiografias ENABLE ROW LEVEL SECURITY;
ALTER TABLE radiografias ENABLE ROW LEVEL SECURITY;
ALTER TABLE eventos_radiografias ENABLE ROW LEVEL SECURITY;
ALTER TABLE notificaciones_radiografias ENABLE ROW LEVEL SECURITY;
CREATE FUNCTION impedir_modificacion_evento_radiografia() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'Los eventos de auditoría son inmutables'; END;
$$;
CREATE TRIGGER eventos_radiografias_inmutables BEFORE UPDATE OR DELETE ON eventos_radiografias
FOR EACH ROW EXECUTE FUNCTION impedir_modificacion_evento_radiografia();
INSERT INTO permisos(nombre,nombre_visible) VALUES
 ('radiografias.read','Consultar radiografías autorizadas'),
 ('radiografias.create','Solicitar radiografías'),
 ('radiografias.update','Gestionar accesos y solicitudes'),
 ('radiografias.audit','Consultar trazabilidad de radiografías');
INSERT INTO permisos_roles(rol_id,permiso_id)
 SELECT r.id,p.id FROM roles r CROSS JOIN permisos p
 WHERE r.nombre IN ('Super Admin','Doctor') AND p.nombre IN ('radiografias.read','radiografias.create','radiografias.update');
INSERT INTO permisos_roles(rol_id,permiso_id)
 SELECT r.id,p.id FROM roles r CROSS JOIN permisos p WHERE r.nombre='Super Admin' AND p.nombre='radiografias.audit';
